apiVersion: v1beta1
kind: AgentConfig
metadata:
  name: ocpdev
#The rendezvousIP must be assigned to a host with the master role
rendezvousIP: 10.85.92.108
hosts:
  - hostname: nyifzsd219.opco.com  # or can use fqdn name here - this is how the bare metal node name will appear in openshift
    role: master
    rootDeviceHints:
#      deviceName: "/dev/sda"
      serialNumber: 0069a224119b3018220028052d604609   # cmd: lsblk -S
#      hctl: "1:2:0:0"  # disk id - cmd: lsblk -S
    interfaces:
      - name: eno1
        macAddress: 24:6e:96:94:a6:50
      - name: eno2
        macAddress: 24:6e:96:94:a6:52
      - name: eno3
        macAddress: 24:6e:96:94:a6:54
      - name: eno4
        macAddress: 24:6e:96:94:a6:55
    networkConfig:
      interfaces:
        - name: bond0.92
          type: vlan
          state: up
          vlan:
            base-iface: bond0
            id: 92
            protocol: 802.1q
          ipv4:
            enabled: true
            address:
              - ip: 10.85.92.108
                prefix-length: 24
            dhcp: false
        - name: bond0
          description: bond eno1 eno2 eno3 eno4
          type: bond
          state: up
          mac-address: 24:6e:96:94:a6:50
          ipv4:
            enabled: false
          ipv6:
            enabled: false
          link-aggregation:
            mode: 802.3ad
            port:
              - eno1
              - eno2
              - eno3
              - eno4
      dns-resolver:
        config:
          server:
            - 10.85.3.20
            - 10.10.3.16
          search:
            - opco.com
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.85.92.1
            next-hop-interface: bond0.92
            table-id: 254
  - hostname: nyifzsd217.opco.com
    role: master
    rootDeviceHints:
      serialNumber: 00f1aeb216ca4d18220001052d604609   # cmd: lsblk -S
#      hctl: "1:2:0:0"  # disk id - cmd: lsblk -S
    interfaces:
      - name: eno1
        macAddress: 24:6e:96:94:8a:80
      - name: eno2
        macAddress: 24:6e:96:94:8a:82
      - name: eno3
        macAddress: 24:6e:96:94:8a:84
      - name: eno4
        macAddress: 24:6e:96:94:8a:85
    networkConfig:
      interfaces:
        - name: bond0.92
          type: vlan
          state: up
          vlan:
            base-iface: bond0
            id: 92
            protocol: 802.1q
          ipv4:
            enabled: true
            address:
              - ip: 10.85.92.106
                prefix-length: 24
            dhcp: false
        - name: bond0
          description: bond eno1 eno2 eno3 eno4
          type: bond
          state: up
          mac-address: 24:6e:96:94:8a:80
          ipv4:
            enabled: false
          ipv6:
            enabled: false
          link-aggregation:
            mode: 802.3ad
            port:
              - eno1
              - eno2
              - eno3
              - eno4
      dns-resolver:
        config:
          server:
            - 10.85.3.20
            - 10.10.3.16
          search:
            - opco.com
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.85.92.1
            next-hop-interface: bond0.92
            table-id: 254
  - hostname: nyifzsd218.opco.com
    role: master
    rootDeviceHints:
      serialNumber: 00a420f612974d18220026052d604609   # cmd: lsblk -S
#      hctl: "1:2:0:0"  # disk id - cmd: lsblk -S
    interfaces:
      - name: eno1
        macAddress: 24:6e:96:94:88:70
      - name: eno2
        macAddress: 24:6e:96:94:88:72
      - name: eno3
        macAddress: 24:6e:96:94:88:74
      - name: eno4
        macAddress: 24:6e:96:94:88:75
    networkConfig:
      interfaces:
        - name: bond0.92
          type: vlan
          state: up
          vlan:
            base-iface: bond0
            id: 92
            protocol: 802.1q
          ipv4:
            enabled: true
            address:
              - ip: 10.85.92.107
                prefix-length: 24
            dhcp: false
        - name: bond0
          description: bond eno1 eno2 eno3 eno4
          type: bond
          state: up
          mac-address: 24:6e:96:94:88:70
          ipv4:
            enabled: false
          ipv6:
            enabled: false
          link-aggregation:
            mode: 802.3ad
            port:
              - eno1
              - eno2
              - eno3
              - eno4
      dns-resolver:
        config:
          server:
            - 10.85.3.20
            - 10.10.3.16
          search:
            - opco.com
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.85.92.1
            next-hop-interface: bond0.92
            table-id: 254
  - hostname: nyifzsd220.opco.com
    role: worker
    interfaces:
      - name: eno5np0
        macAddress: 94:40:c9:6e:c8:48
      - name: eno6np1
        macAddress: 94:40:c9:6e:c8:49
      - name: ens2f0np0
        macAddress: b8:83:03:98:e7:18
      - name: ens2f1np1
        macAddress: b8:83:03:98:e7:19
    networkConfig:
      interfaces:
        - name: bond0.92
          type: vlan
          state: up
          vlan:
            base-iface: bond0
            id: 92
            protocol: 802.1q
          ipv4:
            enabled: true
            address:
              - ip: 10.85.92.120
                prefix-length: 24
            dhcp: false
        - name: bond0
          description: bond nics
          type: bond
          state: up
          mac-address: 94:40:c9:6e:c8:48
          ipv4:
            enabled: false
          ipv6:
            enabled: false
          link-aggregation:
            mode: 802.3ad
            port:
              - eno5np0
              - eno6np1
              - ens2f0np0
              - ens2f1np1
      dns-resolver:
        config:
          server:
            - 10.85.3.20
            - 10.10.3.16
          search:
            - opco.com
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.85.92.1
            next-hop-interface: bond0.92
            table-id: 254
  - hostname: nyifzsd221.opco.com
    role: worker
    interfaces:
      - name: eno5np0
        macAddress: b8:83:03:9d:3b:b0
      - name: eno6np1
        macAddress: b8:83:03:9d:3b:b1
      - name: ens2f0np0
        macAddress: b8:83:03:a2:0b:c9
      - name: ens2f1np1
        macAddress: b8:83:03:a2:0b:c9
    networkConfig:
      interfaces:
        - name: bond0.92
          type: vlan
          state: up
          vlan:
            base-iface: bond0
            id: 92
            protocol: 802.1q
          ipv4:
            enabled: true
            address:
              - ip: 10.85.92.121
                prefix-length: 24
            dhcp: false
        - name: bond0
          description: bond nics
          type: bond
          state: up
          mac-address: b8:83:03:9d:3b:b0
          ipv4:
            enabled: false
          ipv6:
            enabled: false
          link-aggregation:
            mode: 802.3ad
            port:
              - eno5np0
              - eno6np1
              - ens2f0np0
              - ens2f1np1
      dns-resolver:
        config:
          server:
            - 10.85.3.20
            - 10.10.3.16
          search:
            - opco.com
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.85.92.1
            next-hop-interface: bond0.92
            table-id: 254
  - hostname: nyifzsd222.opco.com
    role: worker
    interfaces:
      - name: eno5np0
        macAddress: 94:40:c9:6f:a5:8c
      - name: eno6np1
        macAddress: 94:40:c9:6f:a5:8d
      - name: ens2f0np0
        macAddress: b8:83:03:98:e7:08
      - name: ens2f1np1
        macAddress: b8:83:03:98:e7:09
    networkConfig:
      interfaces:
        - name: bond0.92
          type: vlan
          state: up
          vlan:
            base-iface: bond0
            id: 92
            protocol: 802.1q
          ipv4:
            enabled: true
            address:
              - ip: 10.85.92.122
                prefix-length: 24
            dhcp: false
        - name: bond0
          description: bond nics
          type: bond
          state: up
          mac-address: 94:40:c9:6f:a5:8c
          ipv4:
            enabled: false
          ipv6:
            enabled: false
          link-aggregation:
            mode: 802.3ad
            port:
              - eno5np0
              - eno6np1
              - ens2f0np0
              - ens2f1np1
      dns-resolver:
        config:
          server:
            - 10.85.3.20
            - 10.10.3.16
          search:
            - opco.com
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.85.92.1
            next-hop-interface: bond0.92
            table-id: 254
