apiVersion: v1
baseDomain: opco.com
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    replicas: 3 # Set to 0 for compact cluster (master nodes schedulable)
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3 # Set master 1, compute 0 for single-node cluster
metadata:
  name: ocpdev    #cluster name
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.85.92.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  baremetal:
    apiVIPs:
    - 10.85.92.63
    ingressVIPs:
    - 10.85.92.64
fips: false
pullSecret: '' # client fill in their info here
sshKey: ""   # client fill in their info here
