apiVersion: v1
baseDomain: novadyn.co
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    replicas: 0 # Set to 0 for compact cluster (master nodes schedulable)
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3 # Set to 1 for single-node cluster
metadata:
  name: tx1-ocp-02  # cluster name
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.1.90.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  baremetal:
    apiVIPs:
    - 10.1.90.8
    ingressVIPs:
    - 10.1.90.9
fips: false
pullSecret: ''
sshKey: ""
