apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: unity-<ARRAY_ID>-nfs
provisioner: csi-unity.dellemc.com
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  protocol: NFS
  arrayId: <ARRAY_ID>
  storagePool: <STORAGE_POOL>
  thinProvisioned: "true"
  isDataReductionEnabled: "true"
  #TieringPolicy - Tiering policy to be used during provisioning
  #                Requires FAST VP license.
  # Allowed values: String
  # Optional: true
  # Examples: "0"
  # Default value: None
  # Accepted values:
  #   "0" for "Start High Then Auto-Tier"
  #   "1" for "Auto-Tier"
  #   "2" for "Highest Available Tier"
  #   "3" for "Lowest Available Tier"
  tieringPolicy: <TIERING_POLICY>
  # nasServer - Defines storage NAS Servers. The value should be picked from the column labeled "CLI ID" of NAS Servers tab in the Unisphere GUI.
  # Default value: None
  # Optional: false
  # Examples : nasserver_0
  nasServer: <NAS_SERVER>
  # hostIoSize - Insert Host IO Size that is to be set for the filesystem.
  # Default value: None
  # Optional: false
  # Examples : 8192
  hostIoSize: <HOST_IO_SIZE>
  # csi.storage.k8s.io/fstype - Set the filesystem type; it is ignored with NFS protocol if different from 'nfs'
  # Default value: ext4
  # Accepted values:
  #   "nfs"
  csi.storage.k8s.io/fstype: nfs
# Restrict provisioning to specific topologies
# Allowed values: map of key-value pairs
# Optional: false
# Default value: None
# Examples: "apm0020280XXXX" , "apm0021340XXXX"
# Here first three characters  should be in small letters.
allowedTopologies:
  - matchLabelExpressions:
      - key: csi-unity.dellemc.com/<array_id>-nfs
        values:
          - "true"
# mountOptions - Defines mount input values.
# Default value: []
# Optional: false
# Examples:
#   "hard"    - option for mounting with NFS
#   "context" - option for mounting with block storage
mountOptions: ["<mountOption1>", "<mountOption2>", ..., "<mountOptionN>"]
