apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: githubidp
    mappingMethod: claim
    type: GitHub
    github:
      clientID: Ov23liRgbyDNKRb0A7Vh
      clientSecret:
        name: githubidp-secret
      organizations:
      - nirlep-org
